- name: Install Docker Prerequisites
  apt: 
    name: "{{item}}"
    state: latest
    update_cache: 'yes'
  loop: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common' ]

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu    xenial    stable
    state: present

- name: Install Docker Engine
  apt:
    update_cache: 'yes'
    name: "{{item}}"
    state: latest    
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Pull test Docker Image
  docker_image:
    name: ubuntu
    source: pull